//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub bio: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::user_settings::Entity")]
    UserSettings,
    #[sea_orm(has_many = "super::guild_members::Entity")]
    GuildMembers,
    #[sea_orm(has_many = "super::guilds::Entity")]
    Guilds,
    #[sea_orm(has_many = "super::invites::Entity")]
    Invites,
}

impl Related<super::user_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSettings.def()
    }
}

impl Related<super::guild_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildMembers.def()
    }
}

impl Related<super::invites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invites.def()
    }
}

impl Related<super::guilds::Entity> for Entity {
    fn to() -> RelationDef {
        super::guild_members::Relation::Guilds.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::guild_members::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
